PopCornCinema/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from cinema.views import IndexView, CinemaView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", IndexView.as_view(), name="index"),
    path("movies/", include("cinema.urls")),

    path("about/", CinemaView.as_view(), name="about"),

    path("user/", include("django.contrib.auth.urls")),
    path("user/", include("user.urls")),
    path("cart/", include("cart.urls")),
    path("payment/", include("payment.urls")),

    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .views import *

urlpatterns = [
    path("", CartView.as_view(), name="cart"),
    path('add/', cart_add, name="cart_add"),
    path('delete/', cart_delete, name="cart_delete"),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_name = 'cart'

cart/models.py
from django.db import models


class TicketTemp(models.Model):
    temp_id = models.CharField(max_length=32, unique=True)
    movie_session_id: int = models.IntegerField()
    row: int = models.IntegerField()
    seat: int = models.IntegerField()

    def __hash__(self):
        return hash((self.temp_id, self.movie_session_id, self.row, self.seat))

    def __eq__(self, other):
        if isinstance(other, TicketTemp):
            return (self.movie_session_id == other.movie_session_id and
                    self.row == other.row and
                    self.seat == other.seat)
        return NotImplemented

    def __str__(self):
        return (f'session: {self.movie_session_id!r} '
                f'row: {self.row!r} seat: {self.seat!r} '
                )

cart/views.py
import uuid

from typing import Union

from django.shortcuts import get_object_or_404
from django.views import generic
from django.http import JsonResponse, HttpResponse

from .cart import Cart
from cinema.models import MovieSession
from .models import TicketTemp


# Create your views here.


class CartView(generic.TemplateView):
    template_name = "cart/cart_view.html"

    def get_context_data(self, **kwargs) -> dict:
        context = super().get_context_data(**kwargs)

        cart = Cart(self.request)

        cart_tickets = cart.get_tickets
        context["cart_tickets"] = cart_tickets

        sessions_id: set = {cart_ticket.movie_session_id for cart_ticket in cart_tickets}
        sessions = MovieSession.objects.filter(id__in=sessions_id)

        context["sessions"] = sessions
        context["sessions_titles"] = {session.movie.title for session in sessions}

        context["tickets_summary_price"] = cart.get_summary_tickets_price
        context["tickets_price_sessions"] = cart.get_tickets_price_by_sessions

        return context


def cart_add(request) -> Union[HttpResponse, JsonResponse, None]:
    cart = Cart(request)

    if request.POST.get('action') == "post":
        session_id = int(request.POST.get('session_id'))
        row = int(request.POST.get('row'))
        seat = int(request.POST.get('seat'))

        session = get_object_or_404(MovieSession, id=session_id)

        temp_id = uuid.uuid4()
        ticket = TicketTemp(temp_id=temp_id, movie_session_id=session.id, row=row, seat=seat)

        cart.add(ticket)
        cart_quantity = len(cart)

        response = JsonResponse({"qty": cart_quantity})
        return response


def cart_delete(request):
    cart = Cart(request)
    if request.POST.get('action') == "post":
        ticket_id: str = request.POST.get('ticket_id')
        cart.delete(ticket_id=ticket_id)

        response = JsonResponse({"ticket": ticket_id})
        return response

templates/cart/cart_view.html
{% extends "base.html" %}

{% block content %}
  {% if cart_tickets %}
    <div class="row">
      <div class="col-7">
        {% for session in sessions %}
          <h2>Фільм: {{ session.movie.title }}, Час: {{ session.movie.duration }} Години</h2>
          <h3>Дата: {{ session.string_film_time }}</h3>
          <h3>Ціна: {{ session.price }}</h3>
          {% for cart_ticket in cart_tickets %}
            {% if cart_ticket.movie_session_id == session.id %}
              <div class="row ticket-row">
                <div class="col-sm">Сесія: {{ cart_ticket.movie_session_id }}</div>
                <div class="col-sm">Ряд: {{ cart_ticket.row }}</div>
                <div class="col-sm">Місце: {{ cart_ticket.seat }}</div>
                <button type="button" data-index="{{ cart_ticket.temp_id }}"
                        class="col-sm btn btn-danger delete-ticket">
                  видалити білет
                </button>
              </div>
            {% endif %}
          {% endfor %}
        {% endfor %}
      </div>
      <div class="col-5" id="cart-confirm">
        <div class="cart-buy">
          <h2>Ціна до сплати: {{ cart.get_summary_tickets_price }}</h2>
          {% for price in tickets_price_sessions %}
            <p>{{ price }}</p>
          {% endfor %}
          <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#approvemodal">
            Купити квитки
          </button>
        </div>
      </div>
    </div>

    <script>
        $(document).on("click", ".delete-ticket", function (e) {
            e.preventDefault()
            let ticket_id = $(this).data("index")
            let token = getCookie("csrftoken")
            $.ajax({
                type: "POST",
                url: '{% url "cart:cart_delete" %}',
                data: {
                    csrfmiddlewaretoken: token,
                    ticket_id: ticket_id,
                    action: "post"
                },
                success: function (json) {
                    document.getElementById("cart-quantity").textContent = json.qty

                    location.reload()
                },

                error: function (xhr, errmsg, err) {
                    console.log(err)
                }

            })
        })
    </script>

  {% else %}
    <h2 class="big-buttons-manage">У вас немає білетів у кошику</h2>
  {% endif %}
{% endblock %}

{% if cart_tickets %}
  {% block modal %}
    <div class="modal fade" id="approvemodal" tabindex="-1" role="dialog" aria-labelledby="approvemodal"
         aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="approvemodal">Підтвердження оплати</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <p>Ви впевнені, Що хочете зробити замовлення квитків на:
              {% for session in sessions_titles %}
                <br>{{ session }}
              {% endfor %}?
            </p>
          </div>
          <div class="modal-footer">
            {% if user.is_authenticated %}
            <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">Змінити квитки</button>
            <a href="{% url "payment-home" %}" type="button" class="btn btn-primary">Так</a>
            {% else %}
              <p>Для підтвердження ви повинні зареєструватися або увійти в особистий кабінет</p>
            {% endif %} 
          </div>
        </div>
      </div>
    </div>
  {% endblock %}
{% endif %}