PopCornCinema/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from cinema.views import IndexView, CinemaView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", IndexView.as_view(), name="index"),
    path("movies/", include("cinema.urls")),

    path("about/", CinemaView.as_view(), name="about"),

    path("user/", include("django.contrib.auth.urls")),
    path("user/", include("user.urls")),
    path("cart/", include("cart.urls")),
    path("payment/", include("payment.urls")),

    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .views import *

urlpatterns = [
    path("", CartView.as_view(), name="cart"),
    path('add/', cart_add, name="cart_add"),
    path('delete/', cart_delete, name="cart_delete"),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_name = 'cart'

cinema/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from cinema.views import MoviesDetailView, MoviesListView, MovieSessionDetailView, CinemaListView

urlpatterns = [
    path("", MoviesListView.as_view(), name="movies-list"),
    path("<int:pk>", MoviesDetailView.as_view(), name="movies-detail"),
    path("sessions/<int:pk>/order/", MovieSessionDetailView.as_view(), name="movie_session_order"),
    path("cinemahalls", CinemaListView.as_view(), name="cinema_hall_list_view")
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_name = "cinema"

user/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from user.views import (UserCreateView, UserDetailView, UserUpdateView, order_pdf_download_view,
                        UserDeleteView, OrderListUserView, user_update_password_view)

app_name = "user"

urlpatterns = [
    path("<int:pk>/", UserDetailView.as_view(), name="user-account-detail"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("<int:pk>/update/", UserUpdateView.as_view(), name="update"),
    path("update_password/", user_update_password_view, name="update-password"),
    path("<int:pk>/delete/", UserDeleteView.as_view(), name="delete"),
    path("<int:pk>/orders/", OrderListUserView.as_view(), name="order"),
    path("pdf/<int:pk>", order_pdf_download_view, name="pdf"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/footer.html
<footer class="container">
        <div class="contact-us">
            <p>Виникли питання? <br> Позвоніть чи напишіть нам на почту : </p>
        </div>
        <div class="contact-us">
            <pre class="pre-us">
                olefinibrabus@gmail.com
                +123 12 123 12 12
            </pre>
        </div>
  <div class="links">
    <a class="contact-us logo" href="{% url "about" %}"> Про нас/мапа</a>
  </div>
</footer>

templates/includes/sidebar.html
{% load static %}
<header>
  <div class="nav container">
    <div class="nav-head">
      <a href="{% url "index" %}" class="logo">

        PopCorn <span>Cinema</span>
      </a>
      <form action="{% url "cinema:movies-list" %}" method="get">
        <div class=" log_margin">
          <form action="{% url "cinema:movies-list" %}" method="get" class="form-inline">
            {{ search_form.title }}
            <input type="submit" value="Пошук" class="btn btn-primary">
          </form>
        </div>
      </form>

      {% if user.is_authenticated %}
        <a href="{% url 'user:user-account-detail' pk=user.id %}"
           class="log_margin nav-text">{{ user.first_name }}</a>

        <a href="{% url 'logout' %}" class="log_margin nav-text">Вийти з акаунту</a>
      {% else %}
        <a href="{% url "login" %}" class="log_margin nav-text"> Увійти в аккаунт</a>
        <a href="{% url "user:register" %}" class="log_margin nav-text">Зареєструватися</a>

      {% endif %}

    </div>
  </div>
  <div class="nav-buttons">
    <div class="navbar  row">
      <a href="{% url "index" %}" class="nav-link col">
        <i class='bx bx-home-alt'></i>
        <span class="nav-link-title">Головна</span>
      </a>

      <a href="{% url "cinema:cinema_hall_list_view" %}" class="nav-link col">
        <i class='bx bx-compass'></i>
        <span class="nav-link-title">Кінотеатри</span>
      </a>
      <a href="{% url "cinema:movies-list" %}" class="nav-link col">
        <i class='bx bx-camera-movie'></i>
        <span class="nav-link-title">Навігація</span>
      </a>

      <a href="{% url "cart:cart" %}" class="nav-link col" style="container: body"
         data-toggle="tooltip" data-placement="top" title="Ціна: {{ cart.get_summary_tickets_price }}">
        <i class='bx bxs-cart'></i>
        <div style="display: flex; align-items: center">
          <span class="nav-link-title" style="margin-right: 10px">Кошик</span>
          <span class="nav-link-title " id="cart-quantity">{{ cart|length }}</span>
        </div>
      </a>
    </div>
  </div>

</header>