PopCornCinema/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from cinema.views import IndexView, CinemaView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", IndexView.as_view(), name="index"),
    path("movies/", include("cinema.urls")),

    path("about/", CinemaView.as_view(), name="about"),

    path("user/", include("django.contrib.auth.urls")),
    path("user/", include("user.urls")),
    path("cart/", include("cart.urls")),
    path("payment/", include("payment.urls")),

    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .views import *

urlpatterns = [
    path("", CartView.as_view(), name="cart"),
    path('add/', cart_add, name="cart_add"),
    path('delete/', cart_delete, name="cart_delete"),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_name = 'cart'

cinema/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from cinema.views import MoviesDetailView, MoviesListView, MovieSessionDetailView, CinemaListView

urlpatterns = [
    path("", MoviesListView.as_view(), name="movies-list"),
    path("<int:pk>", MoviesDetailView.as_view(), name="movies-detail"),
    path("sessions/<int:pk>/order/", MovieSessionDetailView.as_view(), name="movie_session_order"),
    path("cinemahalls", CinemaListView.as_view(), name="cinema_hall_list_view")
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_name = "cinema"

cinema/models.py
import os
import uuid
from datetime import datetime, date
from typing import Union

from django.core.exceptions import ValidationError
from django.db import models
from django.conf import settings
from django.utils.text import slugify


class Cinema(models.Model):
    name = models.CharField(max_length=255)
    hall_capacity = models.IntegerField()
    description = models.CharField(
        max_length=511,
        default="Новий кінотеатр"
    )

    def __str__(self):
        return f"Кінотеатр знаходиться: {self.name}, Кількість залів: {self.hall_capacity}"


class CinemaHall(models.Model):
    name = models.CharField(max_length=255)
    rows = models.IntegerField()
    seats_in_row = models.IntegerField()
    hall = models.ForeignKey(Cinema, on_delete=models.CASCADE)

    @property
    def capacity(self) -> int:
        return self.rows * self.seats_in_row

    def __str__(self):
        return self.name

    def save(
            self,
            force_insert=False,
            force_update=False,
            using=None,
            update_fields=None
    ):
        print(len(self.hall.cinemahall_set.all()))
        print(self.hall.hall_capacity)
        if len(self.hall.cinemahall_set.all()) >= self.hall.hall_capacity:
            raise ValidationError("Cinema can't add one more Cinema Hall.")
        return super(CinemaHall, self).save(
            force_insert,
            force_update,
            using,
            update_fields
        )


class Genre(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name


class Actor(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)

    def __str__(self):
        return self.first_name + " " + self.last_name


def movie_image_file_path(instance, filename):
    _, extension = os.path.splitext(filename)
    filename = f"{slugify(instance.title)}-{uuid.uuid4()}{extension}"

    return os.path.join("uploads/movies/", filename)


class Movie(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    duration = models.IntegerField()
    genres = models.ManyToManyField(Genre, blank=True)
    actors = models.ManyToManyField(Actor, blank=True)
    is_active = models.BooleanField(default=True)
    image = models.ImageField(null=True, upload_to=movie_image_file_path)

    class Meta:
        ordering = ["title"]

    def __str__(self):
        return self.title


class MovieSession(models.Model):
    show_time = models.DateTimeField()
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    cinema_hall = models.ForeignKey(CinemaHall, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=5, decimal_places=2, default=0)

    class Meta:
        ordering = ["-show_time"]

    @property
    def string_film_time(self) -> str:
        return time_to_string(self.show_time)


def time_to_string(time: Union[datetime, date], hours=True) -> str:
    str_time = ""

    if time.year != datetime.now().year:
        str_time += time.strftime("Рік: %y, ")

    day = time.strftime("%d ")
    str_time += day if day[0] != "0" else day[1:]

    months = ("січня", "лютого", "березня", "квітня", "травня", "червня",
              "липня", "серпня", "вересня", "жовтня", "листопада", "грудня")
    str_time += months[time.month - 1]

    if hours:
        str_time += time.strftime(" %H:%M")

    return str_time


class Order(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )
    amount = models.DecimalField(max_digits=5, decimal_places=2, default=0)

    class Meta:
        ordering = ["-created_at"]

    @property
    def string_created_time(self) -> str:
        return time_to_string(self.created_at)


class Ticket(models.Model):
    movie_session = models.ForeignKey(
        MovieSession, on_delete=models.CASCADE, related_name="tickets"
    )
    order = models.ForeignKey(
        Order, on_delete=models.CASCADE, related_name="tickets"
    )
    row = models.IntegerField()
    seat = models.IntegerField()

    @staticmethod
    def validate_ticket_without_error_message(row, seat, cinema_hall):
        for ticket_attr_value, ticket_attr_name, cinema_hall_attr_name in [
            (row, "row", "rows"),
            (seat, "seat", "seats_in_row"),
        ]:
            count_attrs = getattr(cinema_hall, cinema_hall_attr_name)
            if not (1 <= ticket_attr_value <= count_attrs):
                return False
        return True

    @staticmethod
    def validate_ticket(row, seat, cinema_hall, error_to_raise):
        for ticket_attr_value, ticket_attr_name, cinema_hall_attr_name in [
            (row, "row", "rows"),
            (seat, "seat", "seats_in_row"),
        ]:
            count_attrs = getattr(cinema_hall, cinema_hall_attr_name)
            if not (1 <= ticket_attr_value <= count_attrs):
                raise error_to_raise(
                    {
                        ticket_attr_name: f"{ticket_attr_name} "
                                          f"number must be in available range: "
                                          f"(1, {cinema_hall_attr_name}): "
                                          f"(1, {count_attrs})"
                    }
                )

    def clean(self):
        Ticket.validate_ticket(
            self.row,
            self.seat,
            self.movie_session.cinema_hall,
            ValidationError
        )

    def save(
            self,
            force_insert=False,
            force_update=False,
            using=None,
            update_fields=None,
    ):
        self.full_clean()
        return super(Ticket, self).save(
            force_insert, force_update, using, update_fields
        )

    class Meta:
        unique_together = ("movie_session", "row", "seat")
        ordering = ["row", "seat"]

cinema/forms.py
from django import forms

from cinema.models import Genre, Ticket, Movie


class MoviesSearchForm(forms.Form):
    title = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Пошук фільма",
                "class": "movie-list-input",
            },
        )
    )
    genre = forms.ModelChoiceField(
        queryset=Genre.objects.all(),
        required=False,
        label='Жанр',
        empty_label='Немає',
        widget=forms.Select(
            attrs={
                "class": "movie-list-margin",
            }
        )
    )
    is_active = forms.BooleanField(
        required=False,
        initial=True,
        label='В театрі:',
        widget=forms.CheckboxInput(
            attrs={
                "class": "movie-list-margin",
            }
        )
    )

cinema/views.py
from django.views import generic

from cinema.forms import *
from cinema.models import *


class IndexView(generic.ListView):
    template_name = "cinema/index.html"
    queryset = Movie.objects.filter(is_active=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if Movie.objects.exists():
            main_movie = Movie.objects.get(pk=4)
            context['main_movie'] = main_movie

        return context


class CinemaListView(generic.ListView):
    template_name = "cinema/cinema_list_view.html"
    model = Cinema


class MoviesListView(generic.ListView):
    template_name = "cinema/movie_list.html"
    model = Movie
    paginate_by = 9

    def get_context_data(self, **kwargs):
        context = super(MoviesListView, self).get_context_data(**kwargs)
        context['search_form'] = MoviesSearchForm(data=self.request.GET)
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        title = self.request.GET.get('title')

        genre_id = self.request.GET.get('genre')
        is_active = self.request.GET.get('is_active')

        conditions = {}

        if genre_id:
            conditions['genres'] = genre_id

        if is_active:
            conditions['is_active'] = is_active.lower() != 'true'

        self.request.session['search_params'] = {
            'genre': genre_id,
            'is_active': is_active,
        }

        if title:
            return queryset.filter(title__icontains=title, **conditions)
        return queryset.filter(**conditions)


class MoviesDetailView(generic.DetailView):
    template_name = "cinema/movie_detail.html"
    model = Movie


class CinemaView(generic.ListView):
    template_name = "cinema/about.html"
    model = CinemaHall


class MovieSessionDetailView(generic.DetailView):
    template_name = 'cinema/movie_session_detail.html'
    model = MovieSession

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        movie_session = self.get_object()

        cinema_hall = movie_session.cinema_hall

        rows_range = range(1, cinema_hall.rows + 1)
        seats_range = range(1, cinema_hall.seats_in_row + 1)

        hall_to_html = [
            (r_number + 1,
             [(s_number + 1, bool(Ticket.objects
                                  .filter(row=row, seat=seat, movie_session=movie_session).first()))
              for s_number, seat in enumerate(seats_range)])
            for r_number, row in enumerate(rows_range)
        ]

        context["hall_to_html"] = hall_to_html
        context['movie_session'] = movie_session

        return context

templates/cinema/about.html
{% extends "base.html" %}

{% block title %}
    Про нас
{% endblock %}
{% block content %}
    {% load static %}
    <div class="line-h">
        <h2 class="text-center display-4">Хто ми?</h2>
        <p class="contact-us"> PopCorn Cinema це не просто звичайний кінотеатр. Це ультимативний центр розваг для вас та
            знайомих.</p>

        <p class="text-info">Активних сеансів зараз: {{ cinemahall_list.count }}</p>

        <p>Ласкаво просимо до найкращого кінотеатру в країні, де ми створили ідеальний кінематографічний простір для
            вас! Ось кілька переваг, які зроблять ваше кінематографічне переживання незабутнім:</p>
        <h3 class="text-center">Зручний інтерфейс:</h3>
        <p>Наш зручний та інтуїтивно зрозумілий інтерфейс дає змогу вам легко та швидко обирати фільми, знаходити
            найближчі сеанси та робити бронювання. Ми прагнемо зробити процес вибору фільму таким же приємним, як і сам
            перегляд.</p>
        <h3 class="text-center">Активна підтримка:</h3>
        <p>Наші висококваліфіковані співробітники активно готові допомогти вам у будь-яких питаннях. Чи то інформація
            про розклад, чи то допомога з квитками, чи то рекомендації щодо вибору фільму, наша команда завжди до ваших
            послуг.</p>
        <h3 class="text-center">Захист акаунтів:</h3>
        <p>Ми серйозно ставимося до безпеки ваших даних і особистої інформації. Наша передова система захисту акаунтів
            гарантує, що ваш досвід використання нашого кінотеатру залишиться конфіденційним і безпечним.</p>
        <h3 class="text-center">Великий спектр фільмів:</h3>
        <p>Від новинок голлівудських блокбастерів до незалежних шедеврів і класичних творів кіномистецтва - ми
            пропонуємо широкий вибір фільмів на будь-який смак. Наш репертуар постійно оновлюється, щоб задовольнити
            запити найвибагливіших глядачів.
            Приєднуйтесь до нас, щоб зануритися у світ кіно разом із найкращими умовами, створеними спеціально для вас.
            Відкрийте для себе задоволення кінематографа в нашому кінотеатрі, де ваше задоволення - наш пріоритет!</p>

        <h2 class="text-center display-4">Як до нас добратися?</h2>
        <div class="flex">
            <img src="{% static 'img/img.png' %}" alt="Мапа" class="map-img">
            <div style="margin-left: 2px">
                <pre>
                    Поки-що єдиний кінотеатр знаходиться
                    на вулиці "Райдужна 16а"
                    Робочі часи:
                    
                    Пн-Пт: 8:00-22:00
                    Сб-Нд: 10:00-20:00
                </pre>
            </div>
        </div>
    </div>
{% endblock %}

templates/cinema/cinema_list_view.html
{% extends "base.html" %}

{% block content %}
  {% for cinema in cinema_list %}
    <div class="container ">
      <div class="card">
        <div class="card-header">
          {{ cinema.name }}
        </div>
        <div class="card-body">
          <h5 class="card-title">Кількість кінозалів: {{ cinema.hall_capacity }}</h5>
          <p class="card-text">{{ cinema.description }}</p>
        </div>
      </div>
    </div>
  {% endfor %}
{% endblock %}

templates/cinema/index.html
{% extends "base.html" %}

{% block content %}
{% if main_movie %}
  <section class="home" id="home">
    
      <img src="{{ main_movie.image.url }}" alt="" class="home-img">
    
    <div class="home-text">
      <h1 class="home-title">{{ main_movie.title }}</h1>
      <p>Фільм на {{ main_movie.duration }} години</p>
      <a href="{% url "cinema:movies-detail" main_movie.id %}" class="watch-bth">
        <i class='bx bx-chevron-right'></i>
        <span>Подивитись</span>
      </a>

    </div>
    <h6 class="description">{{ main_movie.description }}</h6>
  </section>
  {% if movie_list %}
    <div class="swiper-btn">
      <div class="swiper-button-prev"></div>
      <div class="swiper-button-next"></div>

    </div>

    <div class="popular-content swiper">
      <div class="swiper-wrapper">
        {% for movie in movie_list %}

          <!-- Movies Box-->
          <div class="swiper-slide">
            <div class="movie-box">
              <img src="{{ movie.image.url }}" alt="{{ movie.title }}" class="movie-box-img">
              <div class="box-text">
                <h2 class="movie-title">{{ movie.title }}</h2>
                {% for genre in movie.genres.all %}
                  <span class="movie-type">{{ genre }}</span>
                {% endfor %}
                <a href="{% url "cinema:movies-detail" movie.id %}" class="watch-bth play-btn">
                  <i class='bx bx-right-arrow'></i>
                </a>
              </div>
            </div>
          </div>


        {% endfor %}
      </div>
    </div>
  {% else %}
    <h2> На жаль, зараз немає фільмів у прокаті</h2>
  {% endif %}
{% endif %}


{% endblock %}

templates/cinema/movie_detail.html
{% extends "base.html" %}

{% block content %}

  <div class="movie-detail">
    <div class="movie-detail-flex">
      <img src="{{ movie.image.url }}" alt="{{ movie.title }}">
      <div class="movie-detail-descriptions">
        <h2 class="display-4">Фільм {{ movie.title }}</h2>
        {% if movie.is_active %}
          <h3>Фільм зараз у прокаті!</h3>
        {% endif %}
        <h3>Жанри:</h3>
        {% if movie.genres %}
          {% for genre in movie.genres.all %}
            <p>{{ genre }}</p>
          {% endfor %}

        {% else %}
          <p>на жаль, зараз жанри фільма не визначені.</p>

        {% endif %}
        <h3>Актори:</h3>
        {% if movie.actors %}
          {% for actor in movie.actors.all %}
            <p>{{ actor }}</p>
          {% endfor %}
        {% endif %}
      </div>
    </div>
    <p>{{ movie.description }}</p>
    {% if movie.is_active and movie.moviesession_set.all %}
      <h3>Активні сеанси:</h3>
      <ul>
        {% for session in movie.moviesession_set.all %}
          <li class="nav-tabs row">
            <div class="col">
              <p>Час: {{ session.string_film_time }}</p>
              <p>Місце: {{ session.cinema_hall }}</p>
              <p>місць: {{ session.cinema_hall.capacity }}</p>
            </div>
            <div class="col">
              <a href="{% url 'cinema:movie_session_order' pk=session.pk %}">
                <input class="btn btn-primary btn-lg" type="button" value="Замовити квитки">
              </a>
            </div>
          </li>
        {% endfor %}
      </ul>
    {% else %}
      <h3>На жаль, у сеансів на фільм зараз немає</h3>
    {% endif %}
  </div>

{% endblock %}

templates/cinema/movie_list.html
{% extends "base.html" %}

{% block content %}
  <div class="heading">
    <h2 class="heading-title">Каталог Фільмів</h2>
    <form action="" method="get" class="form-inline movie-list-heading">
      {{ search_form.as_p }}
      <input type="submit" value="Пошук" class="btn btn-primary ">
    </form>
  </div>

  <div class="movies-content">
    {% if movie_list %}

      {% for movie in movie_list %}
        <div class="movie-box">
          <img src="{{ movie.image.url }}" alt="{{ movie.title }}" class="movie-box-img">
          <div class="box-text">
            <a href="{% url "cinema:movies-detail" movie.id %}">
              Фільм: {{ movie }}, жанри:
              {% for genre in movie.genres.all %}
                <span class="movie-type">{{ genre }}</span>
              {% endfor %}
            </a>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <table>На жаль, в нас зараз немає таких фільмів у прокаті...</table>
    {% endif %}
  </div>

  {% if is_paginated %}
    {% load query_transform %}
    <ul class="pagination nav">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">
            Попередня Сторінка
          </a>
        </li>
      {% endif %}
      <li class="page-item active"><span
        class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span></li>
      {% if page_obj.has_next %}
        <li class="page-item">
          <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">
            Наступна сторінка
          </a>
        </li>
      {% endif %}
    </ul>
  {% endif %}
{% endblock %}

templates/cinema/movie_session_detail.html
{% extends "base.html" %}

{% block content %}
  {% load ticket_filters %}

  <h2>Оберіть місце для сеансу на фільм: {{ movie_session.movie.title }}</h2>
  <h2>{{ movie_session.cinema_hall }} ,{{ movie_session.string_film_time }}</h2>
  
  <ul class="seat-list">
    {{ available_seats }}

    {% for r_number, row in hall_to_html %}

      <li class="seat-row">Ряд {{ r_number }}:

        {% for s_number, seat in row %}
            {% if seat %}
              <div class="seat-button btn nav-active ">
                Місто зайнято
              </div>
            {% else %}
              <button type="button" class="seat-button btn nav-active"
                      data-id="{{ movie_session.id }}" data-row="{{ r_number }}" data-seat="{{ s_number }}" id="add-cart">
                Місто: {{ s_number }}
              </button>
            {% endif %}
        {% endfor %}
      </li>
    {% endfor %}
  </ul>

  <script>
      $(document).on("click", "#add-cart", function (e) {
          e.preventDefault()
          let session_id = $(this).data("id")
          let row = $(this).data("row")
          let seat = $(this).data("seat")
          let token = getCookie("csrftoken")
          $.ajax({
              type: "POST",
              url: '{% url "cart:cart_add" %}',
              data: {
                  session_id: session_id,
                  csrfmiddlewaretoken: token,
                  row: row,
                  seat: seat,
                  action: "post"
              },
              
              success: function (json) {
                  location.reload()
              },
              
              error: function (xhr, errmsg, err){
                  console.log(err)
              }
              
          })
      })
  </script>
  
{% endblock %}

templates/cinema/order_success.html
{% extends "base.html" %}

{% block content %}
    <p>Заказ успішно створенний</p>
{% endblock %}