PopCornCinema/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from cinema.views import IndexView, CinemaView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", IndexView.as_view(), name="index"),
    path("movies/", include("cinema.urls")),

    path("about/", CinemaView.as_view(), name="about"),

    path("user/", include("django.contrib.auth.urls")),
    path("user/", include("user.urls")),
    path("cart/", include("cart.urls")),
    path("payment/", include("payment.urls")),

    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .views import *

urlpatterns = [
    path("", CartView.as_view(), name="cart"),
    path('add/', cart_add, name="cart_add"),
    path('delete/', cart_delete, name="cart_delete"),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_name = 'cart'

user/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from user.views import (UserCreateView, UserDetailView, UserUpdateView, order_pdf_download_view,
                        UserDeleteView, OrderListUserView, user_update_password_view)

app_name = "user"

urlpatterns = [
    path("<int:pk>/", UserDetailView.as_view(), name="user-account-detail"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("<int:pk>/update/", UserUpdateView.as_view(), name="update"),
    path("update_password/", user_update_password_view, name="update-password"),
    path("<int:pk>/delete/", UserDeleteView.as_view(), name="delete"),
    path("<int:pk>/orders/", OrderListUserView.as_view(), name="order"),
    path("pdf/<int:pk>", order_pdf_download_view, name="pdf"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/models.py
from datetime import date, datetime

from django.contrib.auth.models import (
    AbstractUser,
    BaseUserManager)

from django.db import models
from django.utils.translation import gettext as _

from cinema.models import time_to_string


class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError("The given email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = None
    email = models.EmailField(_("email address"), unique=True)
    first_name = models.CharField(max_length=30, blank=False)
    birthday = models.DateField(default=date.today().replace(month=1, day=1))
    number = models.IntegerField(default=0)
    promotional_money = models.DecimalField(default=0, max_digits=6, decimal_places=2)
    card = models.IntegerField(default=1111_1111_1111_1111)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = UserManager()

    @property
    def get_birthday_to_date(self) -> str:
        return self.birthday.strftime("%Y-%m-%d")

    @property
    def time_to_string(self) -> str:
        return time_to_string(self.birthday, hours=False)

user/forms.py
from user.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, SetPasswordForm


class UserCreateForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', "birthday", "number", 'email', "password1", "password2",)


class UserChangedForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', "birthday", "number", 'email', "card",)


class UserPasswordChangedForm(SetPasswordForm):
    class Meta:
        model = User
        fields = ("new_password1", "new_password2")

user/views.py
import io
from os import remove

import qrcode
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import render, redirect
from django.http import FileResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib.utils import ImageReader
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase import pdfmetrics

from cinema.models import Ticket, Order
from user.forms import UserCreateForm, UserChangedForm, UserPasswordChangedForm
from user.models import User


class UserDetailView(LoginRequiredMixin, generic.DetailView):

    model = User
    template_name = 'user/account.html'
    context_object_name = 'user'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        orders = Order.objects.filter(user=user)
        tickets = Ticket.objects.filter(order__user=user)
        context["orders"] = orders
        context["tickets"] = tickets

        return context


class UserCreateView(generic.CreateView):
    form_class = UserCreateForm
    success_url = "/user/login/"
    template_name = "user/register.html"


class UserUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = User
    form_class = UserChangedForm
    success_url = "/"
    template_name = "user/update.html"


def user_update_password_view(request):
    user = request.user
    if user.is_authenticated:
        if request.method == "POST":
            pass
        else:
            form = UserPasswordChangedForm(user)
            return render(request, "user/update_password.html", {"form": form})
    else:
        messages.success(request, "Ви не зареєстровані")
        redirect("index")


class UserDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = User
    fields = ['first_name', 'last_name', "birthday", "number", 'email', 'card']
    template_name = "user/delete_confim.html"


class OrderListUserView(LoginRequiredMixin, generic.ListView):
    model = Order
    template_name = 'user/order_list_user_view.html'
    paginate_by = 10

    ordering = ['-created_at']


@login_required
def order_pdf_download_view(request, pk):
    if request.method == 'GET':
        order = Order.objects.filter(id=pk).first()
        tickets = Ticket.objects.filter(order=order)

        buffer = io.BytesIO()
        c = canvas.Canvas(buffer, pagesize=letter)

        width, height = letter
        pdfmetrics.registerFont(TTFont('Monaco', 'static/pdf_font/Monaco.ttf'))

        for ticket in tickets:
            c.setFillColor(colors.red)
            c.rect(0, 0, width, height, fill=1)

            c.setFillColor(colors.white)
            margin = 0.5 * inch
            c.rect(margin, margin, width - 2 * margin, height - 2 * margin, fill=1)

            c.setFont("Monaco", 14)
            c.setFillColor(colors.black)

            generate_qrcode_image(ticket, order)

            c.drawString(margin + inch, height - margin - 2.2 * inch, f"Фильм: {ticket.movie_session.movie.title}")
            c.drawString(margin + inch, height - margin - 2.4 * inch, f"Час: {ticket.movie_session.string_film_time}")
            c.drawString(margin + inch, height - margin - 2.6 * inch, f"Місто: {ticket.row}, Ряд: {ticket.seat}")
            c.drawString(margin + inch, height - margin - 2.8 * inch, f"Ціна заказу: {order.amount}")
            c.drawString(margin + inch, height - margin - 2 * inch, f"Дата заказу: {order.string_created_time}")
            c.drawImage(ImageReader("qrcode.png"), 100, 100, height=200, width=200)

            remove("qrcode.png")

            c.line(100, 650, 500, 650)
            c.line(100, 300, 500, 300)
            c.setFillColorRGB(0.5, 0, 0)
            c.drawString(margin + inch, height - margin - 1 * inch, "PopCornCinema")

            c.showPage()
        c.save()

        buffer.seek(0)
        return FileResponse(buffer, as_attachment=True, filename=f"Білети-{order.id}-PopCornCinema.pdf")


def generate_qrcode_image(ticket: Ticket, order: Order, filename='qrcode.png'):
    ticket_values = (ticket.movie_session.movie.title, ticket.movie_session.string_film_time,
                     str(ticket.row), str(ticket.seat), str(order.amount), order.string_created_time)
    a = "".join(ticket_values).replace(" ", ";")
    img = qrcode.make(a)
    img.save(filename)

templates/user/account.html
{% extends "base.html" %}

{% block title %}
  Аккаунт: {{ user.first_name }}
{% endblock %}

{% block content %}
  <h2 class="text-center display-4" style="margin-bottom: 25px"> Основна інформація:</h2>
  <div class="row">
    <div class="col-3">
      <p>Імʼя: </p>

      {% if user.last_name %}
        <p>Фамілія: </p>
      {% endif %}

      <p>День народження:</p>
      <p>Пошта: </p>
      <p>Телефон: </p>
      <p>Картка: </p>
    </div>
    <div class="col-2">
      <p>{{ user.first_name }}</p>
      {% if user.last_name %}
        <p>{{ user.last_name }}</p>
      {% endif %}
      <p>{{ user.time_to_string }}</p>
      <p>{{ user.email }}</p>
      <p>{{ user.number }}</p>
      <p>{{ user.card }}</p>
    </div>
  </div>

  <div class="row">
    <a href="{% url "user:update" pk=user.id %}" class="user-account-btn col"
       data-toggle="tooltip" data-placement="top" title="Змінити данні">
      <i class='bx bxs-pencil bx-md'></i>
    </a>

    <a href="{% url "user:update-password"%}" class="user-account-btn col"
       data-toggle="tooltip" data-placement="top" title="Змінити пароль та пошту">
      <i class='bx bx-lock-alt bx-md'></i>
    </a>

    <a href="{% url "user:delete" pk=user.id %}" class="user-account-btn col"
       data-toggle="tooltip" data-placement="top" title="Видалити акаунт">
      <i class='bx bxs-message-alt-x bx-md'></i>
    </a>

    <a href="{% url "user:order" pk=user.id %}" class="user-account-btn col"
       data-toggle="tooltip" data-placement="top" title="Подивитися закази">
      <i class='bx bx-note bx-md'></i>
    </a>

  </div>

  <div class="user-info promotional">
    <h2>Бонуси: </h2>
    <h3 class="description">{{ user.promotional_money }}</h3>
  </div>

{% endblock %}

templates/user/delete_confim.html
{% extends "base.html" %}

{% block content %}
  <div class="big-buttons-manage">
    <h2>Видалення акаунту</h2>

    <p>Ви згодні, що ваш акаунт, буде назавжди видалено без права на відновлення?</p>

    <form action="" method="post">
      {% csrf_token %}
      <input type="submit" value="Так, я згоден" class="btn btn-danger btn-lg">
    </form>
  </div>
{% endblock %}

templates/user/order_list_user_view.html
{% extends "base.html" %}

{% block content %}
  {% if order_list %}
      {% for order in order_list %}
        <div class="row ticket-row">
        
          <div class="col-sm">{{ order.string_created_time }}</div>
          
          <div class="col-sm">{{ order.amount }}</div>

          <a href="{% url "user:pdf" order.id %}" class="col-sm">
            <i class='bx bxs-file-pdf bx-lg'></i>
          </a>
        
        </div>
      {% endfor %}
    
  {% else %}
    <p class="description">Ви не маєте поки що білетів.</p>
  {% endif %}

  {% if is_paginated %}
    <ul class="pagination nav">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a href="?page={{ page_obj.previous_page_number }}" class="page-link">
            Попередня Сторінка
          </a>
        </li>
      {% endif %}
      <li class="page-item active"><span
        class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span></li>
      {% if page_obj.has_next %}
        <li class="page-item">
          <a href="?page={{ page_obj.next_page_number }}" class="page-link">
            Наступна сторінка
          </a>
        </li>
      {% endif %}
    </ul>
  {% endif %}
{% endblock %}

templates/user/register.html
{% extends "base.html" %}

{% block content %}

  <form class="manage-user" action="" method="post" novalidate>
    {% csrf_token %}
    <h2 class="contact-us">Зареєструватися:</h2>
    <br>
    <label for="first_name">
      Імʼя
      {{ form.first_name }}
    </label>
    <label for="last_name">
      Фамілія
      {{ form.last_name }}
    </label>
    <label for="birthday">
      День народження
      <input type="date" id="id_birthday" name="birthday" value="{{ form.birthday.value }}">
    </label>
    <label for="number">
      Телефоний номер
      {{ form.number }}
    </label>
    <label for="email">
      Електонна пошта
      {{ form.email }}
    </label>
    <label for="password1">
      Пароль
      {{ form.password1 }}
    </label>
    <label for="password2">
      Підтвердити пароль
      {{ form.password2 }}
    </label>
    <ul>
      <li>Ваш пароль не повинен бути занадто схожим на іншу вашу особисту інформацію.</li>
      <li>Ваш пароль повинен містити щонайменше 8 символів.</li>
      <li>Ваш пароль не може бути загальновживаним.</li>
      <li>Ваш пароль не може бути повністю цифровим.</li>
    </ul>

    <input class="btn btn-primary btn-lg" type="submit" value="Submit">
  </form>
{% endblock %}

templates/user/update.html
{% extends "base.html" %}

{% block content %}

  <form class="manage-user" action="" method="post" novalidate>
    {% csrf_token %}
    <h2 class="contact-us">Змінити аккаунт:</h2>
    <br>
    <label for="first_name">
      Імʼя
      {{ form.first_name }}
    </label>
    <label for="last_name">
      Фамілія
      {{ form.last_name }}
    </label>
    <label for="birthday">
      День народження
      <input type="date" id="id_birthday" name="birthday" value="{{ user.get_birthday_to_date }}">
    </label>
    <label for="number">
      Телефоний номер
      {{ form.number }}
    </label>
    <label for="email">
      Електонна пошта
      {{ form.email }}
    </label>
    <label for="card">
      Введіть картку:
      {{ form.card }}
    </label>
    <br>
    <button class="btn btn-primary btn-lg" type="submit">Оновити данні</button>
  </form>
{% endblock %}

templates/user/update_password.html
{% extends "base.html" %}

{% block content %}
  <form class="manage-user" action="" method="post" novalidate>
    {% csrf_token %}
    <h2 class="contact-us">Змінити пароль:</h2>
    <label for="new_password1">
      Новий пароль
      {{ form.new_password1 }}
    </label>
    <label for="new_password2">
      Підтвердити пароль
      {{ form.new_password2 }}
    </label>
    <ul>
      <li>Ваш пароль не повинен бути занадто схожим на іншу вашу особисту інформацію.</li>
      <li>Ваш пароль повинен містити щонайменше 8 символів.</li>
      <li>Ваш пароль не може бути загальновживаним.</li>
      <li>Ваш пароль не може бути повністю цифровим.</li>
    </ul>
    <input class="btn btn-primary btn-lg" type="submit" value="Оновити данні">
  </form>
{% endblock %}